version: '3.8'

services:
  db:
    image: postgres:15
    container_name: avanamy-postgres
    restart: always
    environment:
      POSTGRES_USER: avanamy
      POSTGRES_PASSWORD: avanamy_password
      POSTGRES_DB: avanamy_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: